### ISSUE TITLE
load image.bin file at booting

### ISSUE THREAD

**Issue by satar1980** [robot9706/F1C200S-FUN#1]
I tried to load image.bin file while booting from sdcard but failed when runprog() procedure was executed. can you give me a correct example sir?

```
#define FW_MAGIC 0x555AAAFF
#define RAM_BASE 0x80000000
#define BL1_SIZE 0x40000
#define LOAD_ADDR (RAM_BASE + BL1_SIZE)
static uint32_t loadAddress = LOAD_ADDR;

typedef struct
{
    uint32_t jump_instr;
    uint32_t magic;
    uint32_t start;
    uint32_t end;
    uint32_t reserved;
    uint32_t crc32;
}fw_header_t;

void run_prog()
{
     arm32_interrupt_disable(); // Disable IRQs so nothing is going to stop us
     intc_set_irq_base(LOAD_ADDR);
     v5_cache_inv_range(LOAD_ADDR, loadAddress);               

     void (*bootFunc)(void) = (void (*)())LOAD_ADDR;
     bootFunc();
}

int main(void)
{
	FATFS fs;
        system_init(); 
 
        if(f_mount(&fs, "0:", 1))
	{
		while(1);
	}  

       FIL imgfile;
    
    FRESULT state = f_open(&imgfile, "0:/image.bin", FA_READ);
    if (state != FR_OK)
	{
		printf("open filed \n");
	}
	
	uint8_t buf[80*1024];
		
	state = f_read(&imgfile,  (uint8_t*)buf, sizeof(fw_header_t), NULL);
    
    fw_header_t * hdr = (fw_header_t *)buf;
    if ((hdr->magic == FW_MAGIC) && (hdr->end > hdr->start))
    {
        uint32_t len = hdr->end - hdr->start;
        
        state = f_read(&imgfile,  (uint8_t*)buf, len, NULL);
		if (state != FR_OK)
		{
			printf("read filed \n");
		}
		
	  memcpy((void *)loadAddress, buf, len);
	  
          run_prog(); // failed........ just hang
    }
}
```

**Comment by robot9706** [comment]
Hi! I'm not exactly sure what you are trying to achieve.
But based on the source you provided, your binaries have a header (`fw_header_t`) so the entrypoint might not be where it should or the `jump_instr` points to an invalid address, so you need to make sure your header is correct.
However I think what is more likely is that your binary is not linked to run from `LOAD_ADDR`, when building it you need to link it with a base address of 0x80040000, if it's linked to somewhere else but you don't load it to that address it won't work.

If you check out my CDC v1 loader it expects everything to run from [`0x800200000`](https://github.com/robot9706/F1C200S-FUN/blob/ac274c363e913bc7e04e7e3bdb48a619d1cfd9cd/src/bootloader-env/bootloader-cdc/src/main.c#L17), and everything is then linked to that address [like here](https://github.com/robot9706/F1C200S-FUN/blob/ac274c363e913bc7e04e7e3bdb48a619d1cfd9cd/src/bootloader-env/helloworld/f1c200s_dram.ld#L12).

Also you need to make sure `intc_set_irq_base` is called with the correct address of the interrupt table, if your binary has one, otherwise you don't need to call that function.

**Comment by satar1980** [comment]
from your previous explanation, I made changes by removing the header on the image file and finally it was successfully loaded. thank you very much. now I can save the image.bin file on the fat32 sdcard and run it by the loader when booting.

but I'm still wondering why if I add a header to the vector.S file, the file cannot be loaded by the loader? do you know about it? This is a example of the vector.S file

```
#include "linkage.h"

 /*  I add this header ............ */
 b _image_start
 .long 0x555AAAFF
 .long(__image_start)
 .long(__image_end)
 .long 0
 .long 0
 /* end of header ............ */

.weak _image_start
_image_start:

.globl _start
_start:

_vector:
 b reset
 ldr pc, _undefined_instruction
 ldr pc, _software_interrupt
 ldr pc, _prefetch_abort
 ldr pc, _data_abort
 ldr pc, _not_used
 ldr pc, _irq
 PC ldr, _fiq

...................................................................
```

**Comment by robot9706** [comment]
If you didn't modify your linker settings only removed the header and it works, I think it might be releated to the vector table.
If you use IRQs for anything and you don't update the INTC IRQ base address then the vector table of the bootloader will be used which can cause all sort of weird bugs.

So basically before jumping to the code you need to call `intc_set_irq_base` with the address of `_vector`, which you could calculate easily. It's basically the address of your image + 5x4 bytes (for the 5 long consts of your header) + the jump instruction (`b _image_start` which is 4 bytes as well I think). Or you could store the address of `_vector` in the header and use that to set the base address.
